// Order ID utilities for Bantoo! App
// This module handles Order ID generation and formatting
// Ready for backend integration

/**
 * Generate Order ID from database ID
 * Order IDs are generated by the database using auto-increment
 * This function formats the display ID based on the database ID
 * @param {number} orderId - Database order ID
 * @returns {string} Formatted order ID (e.g., "JKT-8821")
 */
export function generateOrderId(orderId) {
    // Format: CITY-XXXXX
    // City code can be determined by merchant location or default to JKT
    const cityCode = 'JKT'
    const paddedId = String(orderId).padStart(4, '0')
    return `${cityCode}-${paddedId}`
}

/**
 * Format an existing Order ID for display
 * Ensures consistent format: #CITY-XXXX
 * 
 * @param {string|number} orderId - Raw order ID from database
 * @returns {string} Formatted Order ID (e.g., "#JKT-8821")
 */
export function formatOrderId(orderId) {
    if (!orderId) return '#JKT-0000'

    const idString = orderId.toString()

    // If already in correct format (JKT-XXXX)
    if (idString.includes('-')) {
        return idString.startsWith('#') ? idString : `#${idString}`
    }

    // Convert numeric ID to formatted ID
    return `#${generateOrderId(parseInt(idString))}`
}

/**
 * Parse Order ID to get numeric value
 * Useful for backend API calls
 * 
 * @param {string} formattedOrderId - Formatted order ID (e.g., "#JKT-8821")
 * @returns {number} Raw numeric ID (e.g., 8821)
 */
export function parseOrderId(formattedOrderId) {
    if (!formattedOrderId) return 0
    const match = formattedOrderId.match(/\d+/)
    return match ? parseInt(match[0]) : 0
}

/**
 * Validate Order ID format
 * 
 * @param {string} orderId - Order ID to validate
 * @returns {boolean} True if valid format
 */
export function isValidOrderId(orderId) {
    if (!orderId) return false
    const pattern = /^(#)?[A-Z]{3}-\d{4,}$/
    return pattern.test(orderId.toString())
}
